### PR TITLE
fix: Fixes #157 prevent crash if polkadot.js ext includes evm acct

### LINKED ISSUE #157: [BUG] Error: Expected a valid key to convert, with length 1, 2, 4, 8, 32, 33
**Describe the bug**
If I connect with Polkadot.js Extension and one of the accounts is an EVM account (i.e. 0x____) instead of a Substrate SS58 address then it crashes with browse console error `Error: Expected a valid key to convert, with length 1, 2, 4, 8, 32, 33` unless I know to hide that specific address within Polkadot.js Extension

**To Reproduce**

1. Import an EVM address (e.g. for Moonbeam) into Polkadot.js Extension and don't hide it
2. Click Connect Wallet
3. Click Polkadot.js

**Expected behavior**
It should try/catch and ignore that EVM wallet instead of crashing

**Screenshots**

**Desktop (please complete the following information):**

- OS: [e.g. iOS] macOS 14.1.1
- Browser [e.g. chrome, safari] Brave
- Version [e.g. 22] latest version

**Note**
Once you take on this PR paste a comment with your hand -> ✋ so that people know that someone is working on this issue.

### PR DESCRIPTION
**Pull request by ltfschoen**
Instead of crashing when clicking to connect Polkadot.js Extension and it includes an EVM address, and instead of just ignoring it by returning an empty `<div></div>` this PR proposes to still list the EVM address but prevent the user from clicking in in the account list, and highlight it in red.

A better alternative could be to not use `AiOutlineMeh`, and replace lines 142-154 with just a `return (<div></div>)`

Closes #157

### CODE REVIEW

File: src/components/web3/ConnectButton.tsx [hunk 1]
```diff
@@ -16,7 +16,7 @@ import {
 import Image from 'next/image'
 import Link from 'next/link'
 import { FC, useState } from 'react'
-import { AiOutlineCheckCircle, AiOutlineDisconnect } from 'react-icons/ai'
+import { AiOutlineCheckCircle, AiOutlineDisconnect, AiOutlineMeh } from 'react-icons/ai'
```
Comment (ltfschoen) [inline src/components/web3/ConnectButton.tsx:19]: alternative to ignore evm addresses
```suggestion
import { AiOutlineCheckCircle, AiOutlineDisconnect } from 'react-icons/ai'
```

**Comment by poppyseedDev** [comment]
Sorry that this took so long to test, but it turns out polkadot js extension doesn't allow you to add your an evm account so easily, what I had to do to make it work is to create an account on moonriver export it and then import it on polkadot js.

But the PR works well:

Screenshot 2024-05-22 at 01 32 19

Let me know your wallet address so we can send you 50$ in DOT or BTC :)
